name: Lint/Formatter

on:
  pull_request:

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"  # You can change this to your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest

      - name: Run Ruff formatter
        run: |
          ruff format .
          ruff check .

      - name: Run Pytest
        run: |
          pytest
